### PR TITLE
Add query operators to json api

### PR DESCRIPTION
**Pull request by SergioSoldado**
Hi Tomaxx,

 I don't know if this can be done already as I didn't go through the code thoroughly.
 I want to be able to query stuff based on ranges. For instance if I have a timestamp field and I want to query a range with this patch you can do a GET for instance to <code>http://localhost:5000/?filter[timestamp]=>2020-08-01and<2020-08-03</code> to retrieve entries between those 2 dates.

This patch allows 2 types of queries:
* op value
Where op can be <,<=,>,>=
* op1 value bop op2 value
Where op1 and op2 are like op. And bop is one of "and", "or".

 Please share your opinion.

### CODE REVIEW

**Comment by thomaxxl** [comment]
Hello Sergio,

I can't accept this patch: I don't think it is jsonapi compliant, is it?
If you want to implement this in your code, you can set the `jsonapi_filter` method of your model, for ex.

```python
class MyClass(SAFRSBase, db.Model):
    ...
    jsonapi_filter = your_jsonapi_filter

```

There are other ways to implement custom queries:
* using a `SAFRSBase._s_filter` override, which will be called with the `filter=` url query arguments.
* using a `jsonapi_rpc` decorator

Can you work with this?

**Comment by thomaxxl** [comment]
wait, I think I misunderstood your code and explanation.
Maybe I can add it, I will test later today.

**Comment by SergioSoldado** [comment]
Hey Thomas,

 I totally understand. I wasn't aware of jsonapi, let's drop this and I
will try and come up with a solution after reading more on jsonapi.

BR,
Sergio.

**Comment by SergioSoldado** [comment]
Will come up with better solution

**Comment by thomaxxl** [comment]
Well,

I've been thinking about implementing better filtering but I didn't have the time to implement one. The jsonapi spec is quite liberal regarding filtering strategies https://jsonapi.org/recommendations/#filtering . A bit too liberal imho.

If you manage to implement something generic, I'd be very happy to merge it. There were some ideas here : https://discuss.jsonapi.org/t/share-propose-a-filtering-strategy/257/8 , but no consensus afaik :( .

**Comment by SergioSoldado** [comment]
Yes I was looking at exactly that thread, already has some better
suggestions in terms of syntax. :)

**Comment by thomaxxl** [comment]
I haven't used it, but Drupal seems to have pretty solid jsonapi filtering too: https://www.drupal.org/docs/core-modules-and-themes/core-modules/jsonapi-module/filtering

**Comment by SergioSoldado** [comment]
It seems this style of using brackets [] is called simple filters which
according to
https://flask-rest-jsonapi.readthedocs.io/en/latest/filtering.html only
supports the "eq" operator. BTW that package does have the functionality I
am looking for so I will see what work is needed to integrate it, if any.

**Pull request closed without merging**
